apiVersion: v1
kind: NameSpace
metadata:
    name: devops-ns
    labels:
        team: devops
        tools: cicdtools
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkinsdeployment
    namespace: devops-ns
spec:
    selector:
        matchLabels: 
            name: jenkins
    template:
        metadata:
            labels:
                name: jenkins
        spec:
            containers:
            - name: jenkins
              image: jenkins/jenkins:lts
              ports:
              -  containerPort: 8080
              resources:
                  requests:
                      cpu: "200m"
                      memory: "256Mi"
                  limits:
                      cpu: "500m"
                      memory: "512Mi"
              volumeMounts:
              -   name: jenkinsvol
                  mountPath: /var/jenkins_home
            volumes:
            -  name: jenkinsvol
               persistentVolumeClaim:
                   claimName: jenkinspvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkinspvc
    namespace: devops-ns
spec:
    resources:
        requests:
            storage: 2Gi
    accessModes:
    -  ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
    name: jenkinssvc
    namespace: devops-ns
spec:
    type: NodePort
    selector:
        app: jenkins
    ports:
    - port: 80
      targetPort: 8080