apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    nodeSelector:
      name: workernode  # This Selector should be present on any of the Nodes
    containers:
    -  name:  c1
       image: mongo
       ports:
       - containerPort: 27017