apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
    -  name:  c1
       image: mongo
       ports:
       - containerPort: 27017
    affinity:
       nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:    #Soft Rule
           - weight: 1
             preference:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - workerone