apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nodejsrs
    namespace: test-ns
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nodeapp
    template:
        metadata:
            name: nodeapppod
            labels:
                app: nodeapppod
        spec:
            containers:
            -    name: nodeappcontainer
                 image: dockerhandson/node-app-mss:1
                 ports:
                 -    containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
    name: nodejsappsvc
    namespace: test-ns
spec:
    type: NodePort
    selector:
        app: nodeapppod
    ports:
    -    port: 80
         targetPort: 9981