apiVersion: v1
kind: Pod
metadata:
    name: nodejsapp
    namespace: test-ns
    labels:
        app: nodeapp
spec:
    containers:
    - name: nodeappcontainer
      image: dockerhandson/node-app-mss:1
      ports:
      - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
    name: nodejsappsvc
    namespace: test-ns
spec:
    type: ClusterIP
    selector:
        app: mavenwebapp
    ports:
    -    port: 80
         targetPort: 9981
---