apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
    -  name:  c1
       image: mongo
       ports:
       - containerPort: 27017
    affinity:
       podAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:    #Hard Rule
           - labelSelector:
                 matchExpressions:
                 -  key:  app
                    operator: In
                    values:
                    -  nginx
             topologyKey: "kubernetes.io/hostname"