apiVersion: apps/v1
kind: Deployment
metadata:
    name: springapp
    namespace: test-ns
spec:
    replicas: 1
    selector:
        matchLabels: 
            name: springapp
    template:
        metadata:
            labels:
                name: springapp
        spec:
            containers:
            - name: springappcontainer
              image: dockerhandson/spring-boot-mongo:1
              ports:
              -  containerPort: 8080
              resources:
                  requests:
                      cpu: "200m"
                      memory: "256Mi"
                  limits:
                      cpu: "500m"
                      memory: "512Mi"
              env:
              -   name: MONGO_DB_HOSTNAME
                  value: mongosvc
              -   name: MONGO_DB_USERNAME
                  valueFrom:
                      configMapKeyRef:
                          name: springappconfig
                          key: mongodbusername
              -   name: MONGO_DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: springappsecret
                          key: mongodbpassword
---
apiVersion: v1
kind: Service
metadata:
    name: springappsvc
    namespace: test-ns
spec:
    type: NodePort
    selector:
        name: springapp
    ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: mongodb
    namespace: test-ns
spec:
    selector:
        matchLabels:
            name: mongo
    template:
        metadata:
            name: myapp
            labels:
               app: mongo
        spec:
            containers:
            -    name: mongodbcontainer
                 image:  mongo
                 ports:
                 -   containerPort: 27017
                 env:
                 -   name: MONGO_INITDB_ROOT_USERNAME
                     valueFrom:
                      configMapKeyRef:
                          name: springappconfig
                          key: mongodbusername
                 -   name:  MONGO_INITDB_ROOT_PASSWORD
                     valueFrom:
                      secretKeyRef:
                          name: springappsecret
                          key: mongodbpassword
---
apiVersion: v1
kind: Service
metadata:
    name: mongosvc
    namespace: test-ns
spec:
    type: ClusterIP
    selector:
        app: mongo
    ports:
    -  port: 27017
       targetPort: 27017